补完原版食材的json
Snownee/Cuisine2 pull request #5
Opened 2020-02-09 11:26 UTC by RisingInIris2017

2020-02-09 11:35 UTC, Snownee requested changes

2020-02-09 11:35 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/rabbit_foot.json
> +  "items": [ "rabbit_foot" ],
这个不打算添加了，请参考 #4

2020-02-09 11:37 UTC, Snownee commented
有空可以把它们的标签也加上

2020-02-09 11:38 UTC, Snownee requested changes

2020-02-09 11:38 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/carved_pumpkin.json
> +  "items": [ "carved_pumpkin" ],
用标签与南瓜合并为同一食材

2020-02-09 11:54 UTC, RisingInIris2017 commented on src/main/resources/data/cuisine/cuisine_material/carved_pumpkin.json
> +  "items": [ "carved_pumpkin" ],
南瓜和被雕刻的南瓜，kiwi不会显示通用的标签，只有minecraft的命名空间ID。

2020-02-09 11:55 UTC, RisingInIris2017 commented on src/main/resources/data/cuisine/cuisine_material/rabbit_foot.json
> +  "items": [ "rabbit_foot" ],
已删除。

2020-02-09 11:56 UTC, RisingInIris2017 commented
有标签的我都写的标签，没有标签的才写的item。
应该可以。

2020-02-09 12:07 UTC, Snownee requested changes

2020-02-09 12:07 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/glistering_melon_slice.json
> +  "items": [ "glistering_melon_slice" ],
无此食材

2020-02-09 12:07 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/golden_carrot.json
> +  "items": [ "golden_carrot" ],
无此食材

2020-02-10 02:31 UTC, RisingInIris2017 commented on src/main/resources/data/cuisine/cuisine_material/golden_carrot.json
> +  "items": [ "golden_carrot" ],
金胡萝卜和金西瓜不算吗？那我把它们删掉了。

2020-02-10 02:34 UTC, RisingInIris2017 reviewed
已经全部修改完毕，可以merge了。

2020-02-10 02:35 UTC, RisingInIris2017 reviewed
应该就剩下蛋没有添加了（小声）
添加完了再merge也行。

2020-02-10 03:59 UTC, Snownee requested changes

2020-02-10 03:59 UTC, Snownee commented on src/main/resources/data/cuisine/tags/cuisine_materials/fish.json
> +    "salmon"
分成3种独立食材

2020-02-10 03:59 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/pumpkin.json
> +  "items": [ "pumpkin" ],
"items": [ "pumpkin", "carved_pumpkin" ]

2020-02-10 03:59 UTC, Snownee commented on src/main/resources/data/cuisine/cuisine_material/pumpkin.json
> +  "items": [ "pumpkin" ],
"items": [ "pumpkin", "carved_pumpkin" ]

2020-02-10 04:00 UTC, Snownee commented
鸡蛋已经添加过了，记得留意别的PR，避免冲突

2020-02-10 05:47 UTC, RisingInIris2017 reviewed
好的 准备修改。

2020-02-10 05:52 UTC, RisingInIris2017 commented on src/main/resources/data/cuisine/tags/cuisine_materials/fish.json
> +    "salmon"
这个是标签，应该就是这样写吧？
material那边是分成三个独立的。

2020-02-10 06:15 UTC, Snownee commented on src/main/resources/data/cuisine/tags/cuisine_materials/fish.json
> +    "salmon"
看错。应该是 cuisine:cod，以此类推

2020-02-11 11:37 UTC, merged